### PR TITLE
Add Keyboard Controller

### PR DESCRIPTION
**Pull request by Siliconlad**
This MR does a couple of things:
1. It create a ROS node that reads keyboard arrow inputs and converts them into `geometry_msgs/Twist` messages and sends them to the `/cmd_vel` topic. It was heavily based on the [`turtlesim teleop node`](https://github.com/ros/ros_tutorials/tree/noetic-devel/turtlesim).
2. Deletes the `basic_controller` and `custom_msgs` packages which are no longer useful to us
3. Renames the `spawn.launch` file to `simulation.launch` and adds some comments
4. Creates a new file that is identical to `simulation.launch` except launches the new keyboard controller
5. Fix CI so that it can build the simulation submodule

### CODE REVIEW

**Review by SmejoTT — CHANGES_REQUESTED** [review]
@Siliconlad If I press the arrow key it publishes ```msg``` twice, the first one is only zeros the second one is as expected. Is there a reason why it happens? When I press any other key it publishes ```msg``` with zeros, can we instead add the default case to the switch so we don't send unnecessary ```msgs```. Maybe one key could be set as a stop button that sends ```msg``` with zero velocities. I think we should reset velocity to 0 after each arrow key press so that the robot will stop if we are not using arrow keys.

**Comment by Siliconlad** [comment]
@SmejoTT Yeah, I can add a default case to the switch statement. I tried to change it so that it would stop unless you are continuously pressing the key, but it didn't work. I can look into it further if you want.

**Comment by Siliconlad** [comment]
@SmejoTT That should be fixed now. In terms of the stopping when no keys are pressed, I agree that it would be nice, but I don't know how to do that in C++. I can write another one in Python that will do it and add it to this PR.

However, should these controllers be sending these messages? Or would it be better if the robot slowed down?

**Comment by Siliconlad** [comment]
@SmejoTT I've added a python keyboard controller that behaves the way you describe (i.e stops moving the robot if you stop pressing the arrow keys). It is the default controller launched by `keyboard.launch` although you can change this by adding a `use_python:=false` command line argument when running `roslaunch`.

**Review by SmejoTT — CHANGES_REQUESTED** [review]
@Siliconlad At the moment C++ controller behaves better than before but it is still not what we want. I know that problem is that reading the key blocks the program. Maybe we could try to use webots keyboard library and use similar logic as in [this webots controller](https://github.com/cyberbotics/webots/blob/master/projects/robots/clearpath/moose/controllers/moose_path_following/moose_path_following.c).  The python controller publishes ```msg``` twice first one as expected second one with zeros. It is because we publish ```msg``` with zeros on the release of arrow key or any other key. We sort of want this but in a way that the second ```msg```  get published on the next cycle when we are not pressing the key. It seems to be not possible from the code only if we could detect keyboard events instead of just key presses. This way we could know that on a particular cycle no event happened. Overall the python controller does what we want but I think mentioned webots controller and library performs better. It seems to be more responsive and they also use higher velocities which we should too.

**Comment by Siliconlad** [comment]
I'm not sure I fully understand the problem here. I agree the C++ is not ideal, but the reading of the keyboard is blocking as you mentioned. 

The Python one seems to work as we would want it? But you seem to prefer keyboard events for some reason I don't fully understand. How would be stop the robot after the keyboard event is over if we don't set velocities to 0 when the key is released?

**Comment by SmejoTT** [comment]
@Siliconlad Did you have a look at the [webots controller](https://github.com/cyberbotics/webots/blob/master/projects/robots/clearpath/moose/controllers/moose_path_following/moose_path_following.c). They use ```wb_keyboard_get_key``` (```getKey( )``` in C++) function that returns -1 if nothing is pressed. If nothing is pressed they will set velocity to 0. Have a look and maybe try it in the simulation. You can find the simulation in the webots folder in projects/robots/clearpath/moose. If I press the arrow key there once it sets velocity to desired 3 times and then it is set to 0 when I am not pressing anything. What I want to say is that when I press the arrow key up once I want to move forwards but in our python controller the robot will not move if I press the arrow key just once I have to hold it. From the code perspective, it seems that they are the same but if you try it and use it you can see the difference.

**Comment by Siliconlad** [comment]
@SmejoTT I added another controller in the simulation repo https://github.com/automat-ed/simulation/pull/30 which uses the `webots/Keyboard` class to get input. It works quite well. I configured the `keyboard.launch` file to take in a value between 0 and 2 (inclusive) and based on this launches one of the three keyboard controllers. It defaults to the webots one.

**Review by SmejoTT — APPROVED** [review]
Looks good! Works as described.

**Pull request merged**
